version: "3"

services:
  ef-id-info:
    image: docker.htrc.illinois.edu/services/ef-identifier-info:test2
    # The Play app (ef-id-info) will now be accessed internally via Nginx,
    # so we don't need to expose its port directly to the host anymore.
    # It will communicate with Nginx over the 'services' network.
    ports:
       - "127.0.0.1:9001:9000" # Remove or comment this out
    networks:
      - services
    volumes:
      - ../conf/application.conf:/opt/docker/conf/application.conf:ro
      - ../conf/logback.xml:/opt/docker/conf/logback.xml:ro
      - ./data:/data:ro
    restart: always

  nginx:
    image: nginx:stable-alpine # Use a lightweight Nginx image
    networks:
      - services
    ports:
      - "80:80" # Expose Nginx port 80 to the host's port 80
      # - "443:443" # Uncomment if you plan to use HTTPS
    volumes:
      - ./nginx/conf.d:/etc/nginx/conf.d:ro       # Specific server configs
      # - ./nginx/logs:/var/log/nginx # Optional: for persistent logs
    depends_on:
      - ef-id-info # Ensure ef-id-info starts before Nginx
    restart: always

networks:
  services:
  # Define the custom bridge network